baseURL = 'https://mgjules.dev'
languageCode = 'en-us'
title = 'Michaël Giovanni Jules'

disableKinds = ["taxonomy", "term"]

[params]
description = "A Gopher who creates little minions; the industry calls them microservices."
first_name = "Michaël Giovanni"
full_name = "Michaël Giovanni Jules"
gender = "male"
github = "https://github.com/mgjules"
keywords = ["go", "developer", "resume", "curriculum vitae", "cv", "mauritius"]
last_name = "Jules"
username = "mgjules"
