---
backend:
  name: git-gateway
  branch: main
local_backend: true
site_url: https://mgjules.dev
logo_url: "/assets/uploads/logo.png"
media_folder: public/assets/uploads
public_folder: "/assets/uploads"
publish_mode: editorial_workflow
collections:
  - label: General
    name: general
    editor:
      preview: false
    files:
      - label: Meta
        name: meta
        file: data/meta.json
        fields:
          - label: Base URL
            name: base_url
            widget: string
          - label: Language
            name: lang
            widget: select
            options:
              - label: English
                value: en
          - label: Description
            name: description
            widget: text
          - label: Firstname
            name: first_name
            widget: string
          - label: Lastname
            name: last_name
            widget: string
          - label: Username
            name: username
            widget: string
          - label: Gender
            name: gender
            widget: select
            options:
              - label: Male
                value: male
              - label: Female
                value: female
          - label: Avatar
            name: avatar
            widget: image
            options:
              allow_multiple: false
          - label: Keywords
            name: keywords
            widget: list
      - label: Introduction
        name: introduction
        file: data/introduction.json
        fields:
          - label: Avatar
            name: avatar
            widget: image
            options:
              allow_multiple: false
          - label: Introduction
            name: introduction
            widget: markdown
  - label: Curriculum Vitae
    name: cv
    editor:
      preview: false
    files:
      - label: Links
        name: links
        file: data/cv/links.json
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Url
                name: url
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Open in New Window
                name: new_window
                widget: boolean
                required: false
      - label: Sections
        name: sections
        file: data/cv/sections.json
        fields:
          - label: Sections
            name: sections
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
      - label: Technologies
        name: technologies
        file: data/cv/technologies.json
        fields:
          - label: Technologies
            name: technologies
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Remove Saturation
                name: saturate
                widget: boolean
                required: false
      - label: Experiences
        name: experiences
        file: data/cv/experiences.json
        fields:
          - label: Experiences
            name: experiences
            widget: list
            add_to_top: true
            fields:
              - label: Company
                name: company
                widget: string
              - label: From
                name: from
                widget: datetime
                time_format: false
                date_format: MMM YYYY
                format: MMM YYYY
              - label: To
                name: to
                widget: datetime
                time_format: false
                date_format: MMM YYYY
                format: MMM YYYY
                required: false
              - label: Position
                name: position
                widget: string
              - label: Technologies
                name: technologies
                widget: relation
                multiple: true
                collection: cv
                file: technologies
                search_fields:
                  - technologies.*.name
                display_fields:
                  - technologies.*.name
                value_field: technologies.*.name
              - label: Tasks
                name: tasks
                widget: list
                summary: "{{fields.content}}"
                field:
                  label: Content
                  name: content
                  widget: markdown
      - label: Projects
        name: projects
        file: data/cv/projects.json
        fields:
          - label: Projects
            name: projects
            widget: list
            add_to_top: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Link
                name: link
                widget: string
              - label: Description
                name: description
                widget: markdown
              - label: Technologies
                name: technologies
                widget: relation
                multiple: true
                collection: cv
                file: technologies
                search_fields:
                  - technologies.*.name
                display_fields:
                  - technologies.*.name
                value_field: technologies.*.name
      - label: Contributions
        name: contributions
        file: data/cv/contributions.json
        fields:
          - label: Contributions
            name: contributions
            widget: list
            add_to_top: true
            summary: "{{fields.event}} - {{fields.from}}"
            fields:
              - label: Event
                name: event
                widget: string
              - label: From
                name: from
                widget: datetime
                time_format: false
                date_format: MMM YYYY
                format: MMM YYYY
              - label: To
                name: to
                widget: datetime
                time_format: false
                date_format: MMM YYYY
                format: MMM YYYY
                required: false
              - label: Role
                name: role
                widget: select
                options:
                  - Speaker
                  - Co-speaker
                  - Directed
                  - Co-directed
                  - Founder
                  - Co-founder
              - label: Title
                name: title
                widget: string
                required: false
      - label: Awards
        name: awards
        file: data/cv/awards.json
        fields:
          - label: Awards
            name: awards
            widget: list
            add_to_top: true
            summary: "{{fields.event}} - {{fields.date}}"
            fields:
              - label: Event
                name: event
                widget: string
              - label: Date
                name: date
                widget: datetime
                time_format: false
                date_format: YYYY
                format: YYYY
              - label: Icon
                name: icon
                widget: string
              - label: Result
                name: result
                widget: select
                options:
                  - Winner
                  - Runner-up
                  - Third
              - label: Description
                name: description
                widget: markdown
      - label: Interests
        name: interests
        file: data/cv/interests.json
        fields:
          - label: Interests
            name: interests
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
      - label: Languages
        name: languages
        file: data/cv/languages.json
        fields:
          - label: Languages
            name: languages
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Level
                name: level
                widget: select
                options:
                  - Full professional proficiency
                  - Semi professional proficiency
  - name: posts
    label: Posts
    label_singular: Post
    folder: data/blog/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        time_format: false
        date_format: DD MMM YYYY
        format: DD MMM YYYY
      - label: Author
        name: author
        widget: select
        options:
          - Michaël Giovanni Jules
      - label: Cover Image
        name: cover_image
        widget: image
        options:
          allow_multiple: false
      - label: Summary
        name: summary
        widget: text
      - label: Tags
        name: tags
        widget: relation
        multiple: true
        collection: tags
        search_fields:
          - name
        display_fields:
          - name
        value_field: name
      - label: Body
        name: body
        widget: markdown
  - name: tags
    label: Tags
    label_singular: Tag
    folder: data/blog/tags
    create: true
    identifier_field: name
    editor:
      preview: false
    fields:
      - label: Name
        name: name
        widget: string
